### ISSUE TITLE
Incorrect state

### ISSUE THREAD

**Issue by wishie** [bitvale/Switcher#10]
When I load my view with some switches that are set to the 'off' position, they show the correct graphic, but in the color specified for the 'on' state.

**Comment by wishie** [comment]
I should add, those switches are set 'off' with the following:

`eventStartMonthSwitch?.isChecked = settingDm.eventStartMonthSwitch`

where settingDm.evenStartMonthSwitch is either true or false.

**Comment by bitvale** [comment]
Try to use `setChecked(checked: Boolean, withAnimation: Boolean = true)`
