### ISSUE TITLE
How to use switcherX.setOnCheckedChangeListener(); in java

### ISSUE THREAD

**Issue by benevolent13** [bitvale/Switcher#2]
I have implemented your library in the my project ,which have Java as preferred  language and not kotlin.

**Comment by bitvale** [comment]
Try to use [OnCheckedChangeListener](https://developer.android.com/reference/android/widget/CompoundButton.OnCheckedChangeListener.html):

```
OnCheckedChangeListener listener;

public void setOnCheckedChangeListener(OnCheckedChangeListener listener) {
    this.listener = listener;
}

// And somewhere in code
listener.onCheckedChanged(this, checked);
```

Or create custom interface for listener.
