### ISSUE TITLE
Possibility to make Switcher 3 stage..?

### ISSUE THREAD

**Issue by Swavis** [bitvale/Switcher#3]
@bitvale thanks for this awesome **Switcher** but is there any possibility to make **3 Stage Switcher**, it will be really helpful.
Thanks

**Comment by bitvale** [comment]
Hi!
What is **3 Stage Switcher**?

**Comment by Swavis** [comment]
Hello, 3 stage switcher means a switch with 3 stage which allows the user to change a setting between three states.
