### ISSUE TITLE
Great Library

### ISSUE THREAD

**Issue by UmairAhmed420** [bitvale/Switcher#7]
Hello, is there any way to change the icon of switcher? for example can i change icon to play and pause ty

**Comment by bitvale** [comment]
Hi, it is not supported, because icon is drawn using canvas methods and animation is applied to it while drawing. It is possible to implement, but you need to draw icon by hand and at the same time apply animation to it.

**Comment by UmairAhmed420** [comment]
Thanks,, but i m new in this .... can you tell me how to draw those shape it will be very helpful ... just play and pause canvas draw

**Comment by UmairAhmed420** [comment]
Hi alexander, How are you? Hope i m not disturbing you.. Alexander i m fan
of your work, and i want to know that can you teach me how can i convert
dribble animated design into android project ,
Thanks
