### ISSUE TITLE
the widget's direction wrong in Recyclerview

### ISSUE THREAD

**Issue by BeiHaiCoding** [bitvale/Switcher#8]
![`N64FBK%5@LGV`71TPENLZS](https://user-images.githubusercontent.com/30135449/76583848-484dd380-6515-11ea-8616-8d7aaee36224.png)

As shown in the figure 。
when click widget, I change the checked and notifyItemChanged the adapter . finally the diretion has wrong.

**Comment by bitvale** [comment]
Can you share your implementation of RecyclerView adapter?

**Comment by BeiHaiCoding** [comment]
sure.
 //BaseQuickAdapter
 implementation  'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.30'

**Comment by BeiHaiCoding** [comment]
in adapter
![TIM截图20200313152943](https://user-images.githubusercontent.com/30135449/76599263-9bd51700-653f-11ea-98b8-a526963b9dcd.png)

in Activity
![TIM截图20200313153034](https://user-images.githubusercontent.com/30135449/76599269-9e377100-653f-11ea-8421-9160d21aa004.png)

**Comment by bitvale** [comment]
Please try v1.0.7

**Comment by BeiHaiCoding** [comment]
By the way , use "setchecked(boolean)" or use "setcheck(boolean,true)"  still has wrong in the adapter.
only use  "setcheck(boolean,false)" is right.
