### ISSUE TITLE
Hope add is loading

### ISSUE THREAD

**Issue by AnmLobby** [bitvale/Switcher#9]
Can you add one more wait state?  Because in some cases it takes a while to open

**Comment by bitvale** [comment]
Could you explain a little more in detail what is expected?

**Comment by zaaach** [comment]
@bitvale 应该是点击切换时会有请求操作，想要加个loading状态

**Comment by bitvale** [comment]
I think this is not about this widget, because it is just a switch, not a progress or loading view. Feel free to fork the project and implement the behavior you need.
